import { useEffect, useState } from 'react'
import { zodResolver } from '@hookform/resolvers/zod'
import { useQuery } from '@tanstack/react-query'
import { Controller, useForm } from 'react-hook-form'
import { z } from 'zod'
import { getApiErrorMessage } from '../../api/getApiErrorMessage'
import { tenantKeys } from '../../api/tenantKeys'
import { getTenants } from '../../api/tenantApi'
import DateInput from '../ui/DateInput'
import { formatDateForApi, formatDateForDisplay, getTodayForDisplay, isValidDisplayDate } from '../../utils/date'
const date = z.string().min(1,'Vui lòng nhập ngày').refine(isValidDisplayDate,'Ngày phải theo dd/mm/yyyy và hợp lệ')
const schema=z.object({tenant_id:z.coerce.number().int().positive('Vui lòng chọn người thuê'),is_primary:z.boolean(),move_in_date:date,move_out_date:z.string(),status:z.enum(['ACTIVE','MOVED_OUT'])}).superRefine((v,c)=>{if(v.status==='ACTIVE'&&v.move_out_date)c.addIssue({code:'custom',path:['move_out_date'],message:'Người đang ở không có ngày chuyển đi'});if(v.status==='MOVED_OUT'&&!v.move_out_date)c.addIssue({code:'custom',path:['move_out_date'],message:'Vui lòng nhập ngày chuyển đi'});if(v.move_out_date&&!isValidDisplayDate(v.move_out_date))c.addIssue({code:'custom',path:['move_out_date'],message:'Ngày phải theo dd/mm/yyyy và hợp lệ'});if(v.move_out_date&&isValidDisplayDate(v.move_out_date)&&formatDateForApi(v.move_out_date)<formatDateForApi(v.move_in_date))c.addIssue({code:'custom',path:['move_out_date'],message:'Ngày chuyển đi phải sau ngày vào ở'})})
const defaults={tenant_id:'',is_primary:false,move_in_date:getTodayForDisplay(),move_out_date:'',status:'ACTIVE'}
export default function RoomTenantForm({initialValues=defaults,onSubmit,submitLabel}){const [error,setError]=useState('');const tenantsQuery=useQuery({queryKey:tenantKeys.all,queryFn:getTenants});const form=useForm({resolver:zodResolver(schema),defaultValues:defaults});useEffect(()=>form.reset({...defaults,...initialValues,move_in_date:formatDateForDisplay(initialValues.move_in_date||defaults.move_in_date),move_out_date:formatDateForDisplay(initialValues.move_out_date),is_primary:Boolean(initialValues.is_primary)}),[form,initialValues]);const submit=async(v)=>{setError('');try{await onSubmit({...v,move_in_date:formatDateForApi(v.move_in_date),move_out_date:formatDateForApi(v.move_out_date)})}catch(e){const es=e.response?.data?.errors;if(es)Object.entries(es).forEach(([f,m])=>form.setError(f,{type:'server',message:f==='tenant_id'?'Người thuê này hiện đã được ghi nhận đang ở trong phòng.':f==='is_primary'?'Phòng hiện đã có người chính.':m[0]}));setError(getApiErrorMessage(e))}};const {errors,isSubmitting}=form.formState;const tenants=tenantsQuery.data?.data?.data||[];return <form onSubmit={form.handleSubmit(submit)} className="space-y-4"><div><label className="block text-sm font-medium">Người thuê</label><select className="mt-1 w-full rounded-lg border p-2" {...form.register('tenant_id',{valueAsNumber:true})}><option value="">Chọn người thuê</option>{tenants.map(t=><option key={t.id} value={t.id}>{t.full_name}{t.phone?` · ${t.phone}`:''}{t.identity_number?` · CCCD ${t.identity_number}`:''}</option>)}</select>{errors.tenant_id&&<p className="text-sm text-red-600">{errors.tenant_id.message}</p>}</div><label className="flex items-center gap-2 text-sm"><input type="checkbox" {...form.register('is_primary')}/> Người chính</label><div className="grid gap-4 sm:grid-cols-2"><div><label className="block text-sm font-medium">Ngày vào ở</label><Controller name="move_in_date" control={form.control} render={({field})=><DateInput {...field} placeholder="dd/mm/yyyy" invalid={Boolean(errors.move_in_date)}/>}/>{errors.move_in_date&&<p className="text-sm text-red-600">{errors.move_in_date.message}</p>}</div><div><label className="block text-sm font-medium">Trạng thái</label><select className="mt-1 w-full rounded-lg border p-2" {...form.register('status')}><option value="ACTIVE">Đang ở</option><option value="MOVED_OUT">Đã chuyển đi</option></select></div><div><label className="block text-sm font-medium">Ngày chuyển đi</label><Controller name="move_out_date" control={form.control} render={({field})=><DateInput {...field} placeholder="dd/mm/yyyy" invalid={Boolean(errors.move_out_date)}/>}/>{errors.move_out_date&&<p className="text-sm text-red-600">{errors.move_out_date.message}</p>}</div></div>{error&&<p className="text-sm text-red-600">{error}</p>}<button disabled={isSubmitting||tenantsQuery.isPending} className="rounded-lg bg-slate-900 px-4 py-2 text-sm text-white disabled:opacity-60">{isSubmitting?'Đang lưu...':submitLabel}</button></form>}
