import { useEffect, useState } from 'react'
import { Controller, useForm } from 'react-hook-form'
import DateInput from '../ui/DateInput'
import { formatDateForApi, formatDateForDisplay, getTodayForDisplay, isValidDisplayDate } from '../../utils/date'

export default function UtilityReadingForm({ initialValues = {}, onSubmit, label }) {
  const form = useForm({ defaultValues: { reading_date: getTodayForDisplay(), reading_value: '', note: '' } })
  const [error, setError] = useState('')
  useEffect(() => form.reset({ reading_date: formatDateForDisplay(initialValues.reading_date || getTodayForDisplay()), reading_value: initialValues.reading_value ?? '', note: initialValues.note || '' }), [form, initialValues])
  const submit = async (values) => { setError(''); if (!isValidDisplayDate(values.reading_date)) return setError('Ngày ghi phải theo định dạng dd/mm/yyyy và hợp lệ.'); try { await onSubmit({ reading_date: formatDateForApi(values.reading_date), reading_value: Number(values.reading_value), note: values.note || null }) } catch (e) { const errors = e.response?.data?.errors || {}; const message = errors.reading_date?.[0] || errors.reading_value?.[0]; const friendly = message?.includes('already exists') ? 'Ngày này đã có chỉ số.' : message?.includes('lower than the previous') ? 'Chỉ số mới không được nhỏ hơn chỉ số trước đó.' : message?.includes('initial reading') ? 'Chỉ số đầu tiên không được nhỏ hơn chỉ số ban đầu của đồng hồ.' : message?.includes('next reading') ? 'Chỉ số mới không được lớn hơn chỉ số sau đó.' : message; setError(friendly || e.response?.data?.message || 'Không thể lưu chỉ số.') } }
  return <form onSubmit={form.handleSubmit(submit)} className="space-y-4"><div><label className="block text-sm font-medium">Ngày ghi</label><Controller name="reading_date" control={form.control} rules={{ required: true }} render={({ field }) => <DateInput {...field} placeholder="dd/mm/yyyy" invalid={Boolean(form.formState.errors.reading_date)} />} />{form.formState.errors.reading_date && <p className="mt-1 text-sm text-red-600">Vui lòng nhập ngày ghi.</p>}</div><div><label className="block text-sm font-medium" htmlFor="reading-value">Chỉ số công tơ hiện tại</label><input id="reading-value" type="number" min="0" step="0.01" placeholder="VD: 150" className="mt-1 w-full rounded border p-2" {...form.register('reading_value', { required: true })} /></div><div><label className="block text-sm font-medium" htmlFor="reading-note">Ghi chú</label><textarea id="reading-note" placeholder="Ghi chú (không bắt buộc)" className="mt-1 w-full rounded border p-2" {...form.register('note')} /></div>{error && <p className="text-sm text-red-600">{error}</p>}<button className="rounded bg-slate-900 px-4 py-2 text-sm text-white">{label}</button></form>
}
